# 应用服务 WEB 访问端口
server:
  port: 8088
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  redis:
    host: 127.0.0.1  # 或 localhost
    port: 6379       # 默认端口
    database: 0      # 可选，默认是0
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://106.15.7.132:3306/wms?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
    username: wms
    password: "Zhaoyudong@1994"

#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/wms?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
#    username: root
#    password: "000000dong"

